// Import Stimulus application
import { application } from './application';

// Import and register controllers
import SortableController from './sortable_controller';
import AutoSaveController from './auto_save_controller';
import MenuImportController from './menu_import_controller';
import SidebarController from './sidebar_controller';
import StripeWalletController from './stripe_wallet_controller';
import StateController from './state_controller';
import OrderHeaderController from './order_header_controller';
import OrderTotalsController from './order_totals_controller';
import OrderingController from './ordering_controller';
import LocalizationBulkController from './localization_bulk_controller';
import MenuitemsBulkController from './menuitems_bulk_controller';
import MenusectionsBulkController from './menusections_bulk_controller';
import RestaurantsBulkController from './restaurants_bulk_controller';
import DiscoveredRestaurantDeepDiveController from './discovered_restaurant_deep_dive_controller';
import DiscoveredRestaurantWebScrapeController from './discovered_restaurant_web_scrape_controller';
import RestaurantmenusBulkController from './restaurantmenus_bulk_controller';
import DiscoveredRestaurantsBulkController from './discovered_restaurants_bulk_controller';
import PasswordConfirmationToggleController from './password_confirmation_toggle_controller';
import DisabledActionController from './disabled_action_controller';
import UserplanPlanChangeController from './userplan_plan_change_controller';
import GoLiveProgressController from './go_live_progress_controller';
import SettingsDependenciesController from './settings_dependencies_controller';
import BottomSheetController from './bottom_sheet_controller';
import TabBarController from './tab_bar_controller';
import MenuLayoutController from './menu_layout_controller';
import InlineEditController from './inline_edit_controller';
import MobileTabBarController from './mobile_tab_bar_controller';
import AiImageGeneratorController from './ai_image_generator_controller';
import ScrollspyController from './scrollspy_controller';
import SommelierController from './sommelier_controller';
import GeneratePairingsController from './generate_pairings_controller';
import AiProgressController from './ai_progress_controller';
import WhiskeyAmbassadorController from './whiskey_ambassador_controller';
import InviteStaffController from './invite_staff_controller';
import CameraCaptureController from './camera_capture_controller';
import ThemeToggleController from './theme_toggle_controller';
import QuickAddController from './quick_add_controller';
import SplitBillController from './split_bill_controller';
import OrderNotesController from './order_notes_controller';
import FlashController from './flash_controller';
import SubmitOnEnterController from './submit_on_enter_controller';
import CharCounterController from './char_counter_controller';
import WelcomeModalController from './welcome_modal_controller';
import AllergenFilterController from './allergen_filter_controller';
import AddressAutocompleteController from './address_autocomplete_controller';
import ReceiptRequestController from './receipt_request_controller';
import CollectPaymentController from './collect_payment_controller';
import AutoPayController from './auto_pay_controller';
import CustomerAutoPayController from './customer_auto_pay_controller';
import FloorplanController from './floorplan_controller';
import DemoBookingController from './demo_booking_controller';
import VideoAnalyticsController from './video_analytics_controller';
import CrmKanbanController from './crm_kanban_controller';
import CrmLeadDetailController from './crm_lead_detail_controller';
import ThemePickerController from './theme_picker_controller';
import MenuSearchController from './menu_search_controller';
import WaitTimeController from './wait_time_controller';
import RoleChangeController from './role_change_controller';
import RoleChangeFormController from './role_change_form_controller';
import ClipboardController from './clipboard_controller';

application.register('sortable', SortableController);
application.register('auto-save', AutoSaveController);
application.register('menu-import', MenuImportController);
application.register('sidebar', SidebarController);
application.register('stripe-wallet', StripeWalletController);
application.register('state', StateController);
application.register('order-header', OrderHeaderController);
application.register('order-totals', OrderTotalsController);
application.register('ordering', OrderingController);
application.register('localization-bulk', LocalizationBulkController);
application.register('menuitems-bulk', MenuitemsBulkController);
application.register('menusections-bulk', MenusectionsBulkController);
application.register('restaurants-bulk', RestaurantsBulkController);
application.register('discovered-restaurant-deep-dive', DiscoveredRestaurantDeepDiveController);
application.register('discovered-restaurant-web-scrape', DiscoveredRestaurantWebScrapeController);
application.register('restaurantmenus-bulk', RestaurantmenusBulkController);
application.register('discovered-restaurants-bulk', DiscoveredRestaurantsBulkController);
application.register('password-confirmation-toggle', PasswordConfirmationToggleController);
application.register('disabled-action', DisabledActionController);
application.register('userplan-plan-change', UserplanPlanChangeController);
application.register('go-live-progress', GoLiveProgressController);
application.register('settings-dependencies', SettingsDependenciesController);
application.register('bottom-sheet', BottomSheetController);
application.register('tab-bar', TabBarController);
application.register('menu-layout', MenuLayoutController);
application.register('inline-edit', InlineEditController);
application.register('mobile-tab-bar', MobileTabBarController);
application.register('ai-image-generator', AiImageGeneratorController);
application.register('scrollspy', ScrollspyController);
application.register('sommelier', SommelierController);
application.register('generate-pairings', GeneratePairingsController);
application.register('ai-progress', AiProgressController);
application.register('whiskey-ambassador', WhiskeyAmbassadorController);
application.register('invite-staff', InviteStaffController);
application.register('camera-capture', CameraCaptureController);
application.register('theme-toggle', ThemeToggleController);
application.register('quick-add', QuickAddController);
application.register('split-bill', SplitBillController);
application.register('order-notes', OrderNotesController);
application.register('flash', FlashController);
application.register('submit-on-enter', SubmitOnEnterController);
application.register('char-counter', CharCounterController);
application.register('welcome-modal', WelcomeModalController);
application.register('allergen-filter', AllergenFilterController);
application.register('address-autocomplete', AddressAutocompleteController);
application.register('receipt-request', ReceiptRequestController);
application.register('collect-payment', CollectPaymentController);
application.register('auto-pay', AutoPayController);
application.register('customer-auto-pay', CustomerAutoPayController);
application.register('floorplan', FloorplanController);
application.register('demo-booking', DemoBookingController);
application.register('video-analytics', VideoAnalyticsController);
application.register('crm-kanban', CrmKanbanController);
application.register('crm-lead-detail', CrmLeadDetailController);
application.register('theme-picker', ThemePickerController);
application.register('menu-search', MenuSearchController);
application.register('wait-time', WaitTimeController);
application.register('role-change', RoleChangeController);
application.register('role-change-form', RoleChangeFormController);
application.register('clipboard', ClipboardController);
